//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_usuario()
        {
            this.tbl_carrito = new HashSet<tbl_carrito>();
            this.tbl_compra = new HashSet<tbl_compra>();
            this.tbl_producto = new HashSet<tbl_producto>();
            this.tbl_usuario_direccion = new HashSet<tbl_usuario_direccion>();
        }
    
        public int u_id { get; set; }
        public string u_nombre { get; set; }
        public string u_email { get; set; }
        public string u_clave { get; set; }
        public string u_imagen { get; set; }
        public string u_contacto { get; set; }
        public string u_descrip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_carrito> tbl_carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_compra> tbl_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_producto> tbl_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuario_direccion> tbl_usuario_direccion { get; set; }
    }
}
