//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_carrito
    {
        public int carrito_id { get; set; }
        public Nullable<int> carrito_fk_usuario { get; set; }
        public Nullable<int> carrito_fk_producto { get; set; }
        public int carrito_cantidad { get; set; }
        public Nullable<System.DateTime> carrito_fecha { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
        public virtual tbl_producto tbl_producto { get; set; }
    }
}
