//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMarketplaceEntities : DbContext
    {
        public dbMarketplaceEntities()
            : base("name=dbMarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_carrito> tbl_carrito { get; set; }
        public virtual DbSet<tbl_categoria> tbl_categoria { get; set; }
        public virtual DbSet<tbl_compra> tbl_compra { get; set; }
        public virtual DbSet<tbl_detalle_compra> tbl_detalle_compra { get; set; }
        public virtual DbSet<tbl_direccion> tbl_direccion { get; set; }
        public virtual DbSet<tbl_pago> tbl_pago { get; set; }
        public virtual DbSet<tbl_producto> tbl_producto { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_usuario_direccion> tbl_usuario_direccion { get; set; }
    }
}
