//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_producto()
        {
            this.tbl_carrito = new HashSet<tbl_carrito>();
            this.tbl_detalle_compra = new HashSet<tbl_detalle_compra>();
        }
    
        public int pro_id { get; set; }
        public string pro_nombre { get; set; }
        public string pro_imagen { get; set; }
        public string pro_descrip { get; set; }
        public Nullable<int> pro_precio { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_carrito> tbl_carrito { get; set; }
        public virtual tbl_categoria tbl_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detalle_compra> tbl_detalle_compra { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
