//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_direccion()
        {
            this.tbl_usuario_direccion = new HashSet<tbl_usuario_direccion>();
        }
    
        public int direc_id { get; set; }
        public string direc_pais { get; set; }
        public string direc_provincia { get; set; }
        public string direc_distrito { get; set; }
        public string direc_postal { get; set; }
        public string direc_linea1 { get; set; }
        public string direc_linea2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuario_direccion> tbl_usuario_direccion { get; set; }
    }
}
