//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_compra()
        {
            this.tbl_pago = new HashSet<tbl_pago>();
            this.tbl_detalle_compra = new HashSet<tbl_detalle_compra>();
        }
    
        public int compra_id { get; set; }
        public int compra_fk_usuario { get; set; }
        public int compra_fk_direccion { get; set; }
        public Nullable<System.DateTime> compra_fecha { get; set; }
        public decimal compra_total { get; set; }
        public string compra_metodo_pago { get; set; }
        public string compra_observaciones { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
        public virtual tbl_usuario_direccion tbl_usuario_direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pago> tbl_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detalle_compra> tbl_detalle_compra { get; set; }
    }
}
